/* eslint-disable react-hooks/exhaustive-deps */
import React from 'react';
import { Link } from 'react-router-dom';

const channelData = [
  "T-Series",
  "Cocomelon - Nursery Rhymes",
  "SET India",
  "PewDiePie",
  "Kids Diana Show",
  "Like Nastya",
  "Vlad and Niki",
  "5-Minute Crafts",
  "Zee Music Company",
  "Aaj Tak",
  "EmoGamer",
  "T-Series Bhakti Sagar",
  "Sony Music India",
  "Marshmello",
  "Dude Perfect",
  "Bad Bunny",
  "Whindersson Nunes",
  "Markiplier",
  "Katy Perry",
  "Justin Bieber",
  "BTS",
  "Blackpink",
  "Shakira",
  "Ariana Grande",
  "Taylor Swift",
  "The Ellen Show",
  "VanossGaming",
  "JuegaGerman",
  "Fernanfloo",
  "Logan Paul",
  "James Charles",
  "Ninja",
  "Lindsey Stirling",
  "DanTDM",
  "Emma Chamberlain",
  "MrBeast",
  "Jake Paul",
  "KSI",
  "Vikkstar123",
  "FIFA 21",
  "WWE",
  "PewDiePie T-Series",
  "Brianna",
  "NigaHiga",
  "Jacksepticeye",
  "Roman Atwood Vlogs",
  "Ray William Johnson",
  "Rihanna",
  "Billie Eilish",
  "Dwayne Johnson",
  "Selena Gomez",
  "Chris Brown",
  "Ed Sheeran",
  "Shane Dawson TV",
  "Smosh",
  "Good Mythical Morning",
  "Mark Rober",
  "Logan Paul Vlogs",
  "Walt Disney Animation Studios",
  "National Geographic",
  "Dream",
  "Corpse Husband",
  "Zane Hijazi",
  "Liza Koshy",
  "Tati Westbrook",
  "Jackie Aina",
  "Vanity Fair",
  "Vox",
  "BBC Earth",
  "HBO Max",
  "Netflix",
  "Disney+",
  "Paramount Pictures",
  "Hannah Montana",
  "The Tonight Show Starring Jimmy Fallon",
  "CNET",
  "The Late Show with Stephen Colbert",
  "Vox Media",
  "Full House",
  "NBCUniversal",
  "Instagram",
  "TikTok",
  "YouTube Official",
  "T-Series",
  "Cocomelon - Nursery Rhymes",
  "SET India",
  "PewDiePie",
  "Kids Diana Show",
  "Like Nastya",
  "Vlad and Niki",
  "5-Minute Crafts",
  "Zee Music Company",
  "Aaj Tak",
  "EmoGamer",
  "T-Series Bhakti Sagar",
  "Sony Music India",
  "Marshmello",
  "Dude Perfect",
  "Bad Bunny",
  "Whindersson Nunes",
  "Markiplier",
  "Katy Perry",
  "Justin Bieber",
  "BTS",
  "Blackpink",
  "Shakira",
  "Ariana Grande",
  "Taylor Swift",
  "The Ellen Show",
  "VanossGaming",
  "JuegaGerman",
  "Fernanfloo",
  "Logan Paul",
  "James Charles",
  "Ninja",
  "Lindsey Stirling",
  "DanTDM",
  "Emma Chamberlain",
  "MrBeast",
  "Jake Paul",
  "KSI",
  "Vikkstar123",
  "FIFA 21",
  "WWE",
  "PewDiePie T-Series",
  "Brianna",
  "NigaHiga",
  "Jacksepticeye",
  "Roman Atwood Vlogs",
  "Ray William Johnson",
  "Rihanna",
  "Billie Eilish",
  "Dwayne Johnson",
  "Selena Gomez",
  "Chris Brown",
  "Ed Sheeran",
  "Shane Dawson TV",
  "Smosh",
  "Good Mythical Morning",
  "Mark Rober",
  "Logan Paul Vlogs",
  "Walt Disney Animation Studios",
  "National Geographic",
  "Dream",
  "Corpse Husband",
  "Zane Hijazi",
  "Liza Koshy",
  "Tati Westbrook",
  "Jackie Aina",
  "Vanity Fair",
  "Vox",
  "BBC Earth",
  "HBO Max",
  "Netflix",
  "Disney+",
  "Paramount Pictures",
  "Hannah Montana",
  "The Tonight Show Starring Jimmy Fallon",
  "CNET",
  "The Late Show with Stephen Colbert",
  "Vox Media",
  "Full House",
  "NBCUniversal",
  "Instagram",
  "TikTok",
  "YouTube Official",
  "T-Series",
  "Cocomelon - Nursery Rhymes",
  "SET India",
  "PewDiePie",
  "Kids Diana Show",
  "Like Nastya",
  "Vlad and Niki",
  "5-Minute Crafts",
  "Zee Music Company",
  "Aaj Tak",
  "EmoGamer",
  "T-Series Bhakti Sagar",
  "Sony Music India",
  "Marshmello",
  "Dude Perfect",
  "Bad Bunny",
  "Whindersson Nunes",
  "Markiplier",
  "Katy Perry",
  "Justin Bieber",
  "BTS",
  "Blackpink",
  "Shakira",
  "Ariana Grande",
  "Taylor Swift",
  "The Ellen Show",
  "VanossGaming",
  "JuegaGerman",
  "Fernanfloo",
  "Logan Paul",
  "James Charles",
  "Ninja",
  "Lindsey Stirling",
  "DanTDM",
  "Emma Chamberlain",
  "MrBeast",
  "Jake Paul",
  "KSI",
  "Vikkstar123",
  "FIFA 21",
  "WWE",
  "PewDiePie T-Series",
  "Brianna",
  "NigaHiga",
  "Jacksepticeye",
  "Roman Atwood Vlogs",
  "Ray William Johnson",
  "Rihanna",
  "Billie Eilish",
  "Dwayne Johnson",
  "Selena Gomez",
  "Chris Brown",
  "Ed Sheeran",
  "Shane Dawson TV",
  "Smosh",
  "Good Mythical Morning",
  "Mark Rober",
  "Logan Paul Vlogs",
  "Walt Disney Animation Studios",
  "National Geographic",
  "Dream",
  "Corpse Husband",
  "Zane Hijazi",
  "Liza Koshy",
  "Tati Westbrook",
  "Jackie Aina",
  "Vanity Fair",
  "Vox",
  "BBC Earth",
  "HBO Max",
  "Netflix",
  "Disney+",
  "Paramount Pictures",
  "Hannah Montana",
  "The Tonight Show Starring Jimmy Fallon",
  "CNET",
  "The Late Show with Stephen Colbert",
  "Vox Media",
  "Full House",
  "NBCUniversal",
  "Instagram",
  "TikTok",
  "YouTube Official",
];


const Sidebar = ({ isWatchPage, isMenuOpen }) => {

  // Early return if the menu is closed
  if (!isMenuOpen) return null;

  return (
    <div
      className={`p-5 w-48 shadow-lg bg-white ${
        isWatchPage ? 'absolute' : 'relative'
      }`}
    >
      <ul>
        <Link to="/">
          <li>Home</li>
        </Link>
        <li>Shorts</li>
        <li>Videos</li>
        <li>Live</li>
      </ul>

      <h1 className="font-bold pt-4 text-xl">Subscriptions</h1>
      <ul>
        <li>Music</li>
        <li>Sports</li>
        <li>Gaming</li>
        <li>Movies</li>
      </ul>

      <h1 className="font-bold pt-4 text-xl">Watch Later</h1>
      <ul>
        <li>Music</li>
        <li>Sports</li>
        <li>Gaming</li>
        <li>Movies</li>
      </ul>

      <h1 className="font-bold pt-4 text-lg">Popular Channels</h1>
      <ul className="space-y-2">
        {channelData.map((channel, index) => (
          <li key={index} className="flex items-center space-x-2">
            <span>{channel}</span>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Sidebar;
